### PR TITLE
Adding Dune query for number of unique ORA stackers

### PR DESCRIPTION
**Pull request by hackathonius**

### CODE REVIEW

**Comment by hackathonius** [comment]
Can you please comment why this PR is closed?

**Comment by fewwwww** [comment]
It appears that your change to add the new query is duplicated with the existing content, because the query in your pr is a fork to the second dashboard listed in this repo.

**Comment by hackathonius** [comment]
Yes, can you please include my query to the dashboard then? There is no way for me to edit it.

**Comment by fewwwww** [comment]
The dashboard you are referring to is maintained by Hashed, not ORA.

**Pull request closed without merging**
